/********************************************************************************
** Form generated from reading UI file 'DialogSetting.ui'
**
** Created by: Qt User Interface Compiler version 5.7.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DIALOGSETTING_H
#define UI_DIALOGSETTING_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QSplitter>

QT_BEGIN_NAMESPACE

class Ui_Dialog
{
public:
    QGroupBox *groupBox;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_type;
    QLabel *label_4;
    QLabel *label_5;
    QSpinBox *spinBox_hp_1;
    QSpinBox *spinBox_speed_1;
    QSpinBox *spinBox_attackrange_1;
    QLabel *label_6;
    QSpinBox *spinBox_size_1;
    QSpinBox *spinBox_number_1;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QSpinBox *spinBox_hp_2;
    QSpinBox *spinBox_size_2;
    QLabel *label_10;
    QSpinBox *spinBox_attackrange_2;
    QSpinBox *spinBox_speed_2;
    QLabel *label_type_2;
    QSpinBox *spinBox_number_2;
    QLabel *label_11;
    QSpinBox *spinBox_number_3;
    QSpinBox *spinBox_hp_3;
    QSpinBox *spinBox_size_3;
    QLabel *label_type_3;
    QSpinBox *spinBox_attackrange_3;
    QSpinBox *spinBox_speed_3;
    QLabel *label_12;
    QSpinBox *spinBox_number_4;
    QSpinBox *spinBox_hp_4;
    QSpinBox *spinBox_size_4;
    QLabel *label_type_4;
    QSpinBox *spinBox_attackrange_4;
    QSpinBox *spinBox_speed_4;
    QLabel *label_13;
    QSpinBox *spinBox_number_5;
    QSpinBox *spinBox_hp_5;
    QSpinBox *spinBox_size_5;
    QLabel *label_type_5;
    QSpinBox *spinBox_attackrange_5;
    QSpinBox *spinBox_speed_5;
    QLabel *label_14;
    QSpinBox *spinBox_number_6;
    QSpinBox *spinBox_hp_6;
    QSpinBox *spinBox_size_6;
    QLabel *label_type_6;
    QSpinBox *spinBox_attackrange_6;
    QSpinBox *spinBox_speed_6;
    QLabel *label_15;
    QSpinBox *spinBox_number_7;
    QSpinBox *spinBox_hp_7;
    QSpinBox *spinBox_size_7;
    QLabel *label_type_7;
    QSpinBox *spinBox_attackrange_7;
    QSpinBox *spinBox_speed_7;
    QSpinBox *spinBox_speed_8;
    QLabel *label_16;
    QSpinBox *spinBox_hp_8;
    QSpinBox *spinBox_size_8;
    QLabel *label_type_8;
    QSpinBox *spinBox_attackrange_8;
    QSpinBox *spinBox_number_8;
    QGroupBox *groupBox_2;
    QLabel *label;
    QSpinBox *spinBox_mapWidth;
    QLabel *label_17;
    QSpinBox *spinBox_mapHeight;
    QLabel *label_18;
    QSpinBox *spinBox_boneTime;
    QSpinBox *spinBox_ageTime;
    QLabel *label_19;
    QSpinBox *spinBox_reproduceAge;
    QLabel *label_20;
    QLabel *label_21;
    QSpinBox *spinBox_reproduceHp;
    QLabel *label_22;
    QLabel *label_23;
    QSpinBox *spinBox_reproduceProportion;
    QLabel *label_24;
    QSpinBox *spinBox_ageLimit;
    QLabel *label_25;
    QSpinBox *spinBox_numberLimit;
    QLabel *label_26;
    QSplitter *splitter;
    QPushButton *pushButton_rand;
    QPushButton *pushButton_ok;
    QPushButton *pushButton_load;
    QPushButton *pushButton_save;
    QPushButton *pushButton;

    void setupUi(QDialog *Dialog)
    {
        if (Dialog->objectName().isEmpty())
            Dialog->setObjectName(QStringLiteral("Dialog"));
        Dialog->resize(890, 752);
        groupBox = new QGroupBox(Dialog);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(20, 10, 851, 461));
        QFont font;
        font.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221 Light"));
        font.setPointSize(12);
        groupBox->setFont(font);
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(30, 20, 61, 31));
        QFont font1;
        font1.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font1.setPointSize(12);
        label_2->setFont(font1);
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(150, 20, 61, 31));
        label_3->setFont(font1);
        label_type = new QLabel(groupBox);
        label_type->setObjectName(QStringLiteral("label_type"));
        label_type->setGeometry(QRect(30, 60, 40, 40));
        label_type->setPixmap(QPixmap(QString::fromUtf8(":/ecosystem/Resources/cattle.png")));
        label_type->setScaledContents(true);
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(250, 20, 81, 31));
        label_4->setFont(font1);
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(380, 20, 91, 31));
        label_5->setFont(font1);
        spinBox_hp_1 = new QSpinBox(groupBox);
        spinBox_hp_1->setObjectName(QStringLiteral("spinBox_hp_1"));
        spinBox_hp_1->setGeometry(QRect(140, 70, 61, 22));
        spinBox_hp_1->setMaximum(1000);
        spinBox_hp_1->setValue(1000);
        spinBox_speed_1 = new QSpinBox(groupBox);
        spinBox_speed_1->setObjectName(QStringLiteral("spinBox_speed_1"));
        spinBox_speed_1->setGeometry(QRect(260, 70, 61, 22));
        spinBox_speed_1->setMinimum(1);
        spinBox_speed_1->setMaximum(100);
        spinBox_speed_1->setValue(20);
        spinBox_attackrange_1 = new QSpinBox(groupBox);
        spinBox_attackrange_1->setObjectName(QStringLiteral("spinBox_attackrange_1"));
        spinBox_attackrange_1->setGeometry(QRect(390, 70, 61, 22));
        spinBox_attackrange_1->setMinimum(0);
        spinBox_attackrange_1->setMaximum(100);
        spinBox_attackrange_1->setValue(0);
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(510, 20, 91, 31));
        label_6->setFont(font1);
        spinBox_size_1 = new QSpinBox(groupBox);
        spinBox_size_1->setObjectName(QStringLiteral("spinBox_size_1"));
        spinBox_size_1->setGeometry(QRect(510, 70, 61, 22));
        spinBox_size_1->setMinimum(1);
        spinBox_size_1->setMaximum(100);
        spinBox_size_1->setValue(40);
        spinBox_number_1 = new QSpinBox(groupBox);
        spinBox_number_1->setObjectName(QStringLiteral("spinBox_number_1"));
        spinBox_number_1->setGeometry(QRect(630, 70, 61, 22));
        spinBox_number_1->setMinimum(0);
        spinBox_number_1->setMaximum(100);
        spinBox_number_1->setValue(10);
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(635, 20, 91, 31));
        label_7->setFont(font1);
        label_8 = new QLabel(groupBox);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(730, 20, 101, 31));
        label_8->setFont(font1);
        label_9 = new QLabel(groupBox);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(740, 67, 72, 21));
        label_9->setLayoutDirection(Qt::LeftToRight);
        spinBox_hp_2 = new QSpinBox(groupBox);
        spinBox_hp_2->setObjectName(QStringLiteral("spinBox_hp_2"));
        spinBox_hp_2->setGeometry(QRect(140, 120, 61, 22));
        spinBox_hp_2->setMaximum(1000);
        spinBox_hp_2->setValue(1000);
        spinBox_size_2 = new QSpinBox(groupBox);
        spinBox_size_2->setObjectName(QStringLiteral("spinBox_size_2"));
        spinBox_size_2->setGeometry(QRect(510, 120, 61, 22));
        spinBox_size_2->setMinimum(1);
        spinBox_size_2->setMaximum(100);
        spinBox_size_2->setValue(30);
        label_10 = new QLabel(groupBox);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(740, 117, 72, 21));
        label_10->setLayoutDirection(Qt::LeftToRight);
        spinBox_attackrange_2 = new QSpinBox(groupBox);
        spinBox_attackrange_2->setObjectName(QStringLiteral("spinBox_attackrange_2"));
        spinBox_attackrange_2->setGeometry(QRect(390, 120, 61, 22));
        spinBox_attackrange_2->setMinimum(0);
        spinBox_attackrange_2->setMaximum(100);
        spinBox_attackrange_2->setValue(0);
        spinBox_speed_2 = new QSpinBox(groupBox);
        spinBox_speed_2->setObjectName(QStringLiteral("spinBox_speed_2"));
        spinBox_speed_2->setGeometry(QRect(260, 120, 61, 22));
        spinBox_speed_2->setMinimum(1);
        spinBox_speed_2->setMaximum(100);
        spinBox_speed_2->setValue(20);
        label_type_2 = new QLabel(groupBox);
        label_type_2->setObjectName(QStringLiteral("label_type_2"));
        label_type_2->setGeometry(QRect(30, 110, 40, 40));
        label_type_2->setPixmap(QPixmap(QString::fromUtf8(":/ecosystem/Resources/chick.png")));
        label_type_2->setScaledContents(true);
        spinBox_number_2 = new QSpinBox(groupBox);
        spinBox_number_2->setObjectName(QStringLiteral("spinBox_number_2"));
        spinBox_number_2->setGeometry(QRect(630, 120, 61, 22));
        spinBox_number_2->setMinimum(0);
        spinBox_number_2->setMaximum(100);
        spinBox_number_2->setValue(10);
        label_11 = new QLabel(groupBox);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(740, 167, 72, 21));
        label_11->setLayoutDirection(Qt::LeftToRight);
        spinBox_number_3 = new QSpinBox(groupBox);
        spinBox_number_3->setObjectName(QStringLiteral("spinBox_number_3"));
        spinBox_number_3->setGeometry(QRect(630, 170, 61, 22));
        spinBox_number_3->setMinimum(0);
        spinBox_number_3->setMaximum(100);
        spinBox_number_3->setValue(10);
        spinBox_hp_3 = new QSpinBox(groupBox);
        spinBox_hp_3->setObjectName(QStringLiteral("spinBox_hp_3"));
        spinBox_hp_3->setGeometry(QRect(140, 170, 61, 22));
        spinBox_hp_3->setMaximum(1000);
        spinBox_hp_3->setValue(1000);
        spinBox_size_3 = new QSpinBox(groupBox);
        spinBox_size_3->setObjectName(QStringLiteral("spinBox_size_3"));
        spinBox_size_3->setGeometry(QRect(510, 170, 61, 22));
        spinBox_size_3->setMinimum(1);
        spinBox_size_3->setMaximum(100);
        spinBox_size_3->setValue(35);
        label_type_3 = new QLabel(groupBox);
        label_type_3->setObjectName(QStringLiteral("label_type_3"));
        label_type_3->setGeometry(QRect(30, 160, 40, 40));
        label_type_3->setPixmap(QPixmap(QString::fromUtf8(":/ecosystem/Resources/deer.png")));
        label_type_3->setScaledContents(true);
        spinBox_attackrange_3 = new QSpinBox(groupBox);
        spinBox_attackrange_3->setObjectName(QStringLiteral("spinBox_attackrange_3"));
        spinBox_attackrange_3->setGeometry(QRect(390, 170, 61, 22));
        spinBox_attackrange_3->setMinimum(0);
        spinBox_attackrange_3->setMaximum(100);
        spinBox_attackrange_3->setValue(0);
        spinBox_speed_3 = new QSpinBox(groupBox);
        spinBox_speed_3->setObjectName(QStringLiteral("spinBox_speed_3"));
        spinBox_speed_3->setGeometry(QRect(260, 170, 61, 22));
        spinBox_speed_3->setMinimum(1);
        spinBox_speed_3->setMaximum(100);
        spinBox_speed_3->setValue(20);
        label_12 = new QLabel(groupBox);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(740, 217, 72, 21));
        label_12->setLayoutDirection(Qt::LeftToRight);
        spinBox_number_4 = new QSpinBox(groupBox);
        spinBox_number_4->setObjectName(QStringLiteral("spinBox_number_4"));
        spinBox_number_4->setGeometry(QRect(630, 220, 61, 22));
        spinBox_number_4->setMinimum(0);
        spinBox_number_4->setMaximum(100);
        spinBox_number_4->setValue(10);
        spinBox_hp_4 = new QSpinBox(groupBox);
        spinBox_hp_4->setObjectName(QStringLiteral("spinBox_hp_4"));
        spinBox_hp_4->setGeometry(QRect(140, 220, 61, 22));
        spinBox_hp_4->setMaximum(1000);
        spinBox_hp_4->setValue(1000);
        spinBox_size_4 = new QSpinBox(groupBox);
        spinBox_size_4->setObjectName(QStringLiteral("spinBox_size_4"));
        spinBox_size_4->setGeometry(QRect(510, 220, 61, 22));
        spinBox_size_4->setMinimum(1);
        spinBox_size_4->setMaximum(100);
        spinBox_size_4->setValue(45);
        label_type_4 = new QLabel(groupBox);
        label_type_4->setObjectName(QStringLiteral("label_type_4"));
        label_type_4->setGeometry(QRect(30, 210, 40, 40));
        label_type_4->setPixmap(QPixmap(QString::fromUtf8(":/ecosystem/Resources/elephant.png")));
        label_type_4->setScaledContents(true);
        spinBox_attackrange_4 = new QSpinBox(groupBox);
        spinBox_attackrange_4->setObjectName(QStringLiteral("spinBox_attackrange_4"));
        spinBox_attackrange_4->setGeometry(QRect(390, 220, 61, 22));
        spinBox_attackrange_4->setMinimum(0);
        spinBox_attackrange_4->setMaximum(100);
        spinBox_attackrange_4->setValue(0);
        spinBox_speed_4 = new QSpinBox(groupBox);
        spinBox_speed_4->setObjectName(QStringLiteral("spinBox_speed_4"));
        spinBox_speed_4->setGeometry(QRect(260, 220, 61, 22));
        spinBox_speed_4->setMinimum(1);
        spinBox_speed_4->setMaximum(100);
        spinBox_speed_4->setValue(20);
        label_13 = new QLabel(groupBox);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(740, 417, 72, 21));
        label_13->setLayoutDirection(Qt::LeftToRight);
        spinBox_number_5 = new QSpinBox(groupBox);
        spinBox_number_5->setObjectName(QStringLiteral("spinBox_number_5"));
        spinBox_number_5->setGeometry(QRect(630, 420, 61, 22));
        spinBox_number_5->setMinimum(0);
        spinBox_number_5->setMaximum(100);
        spinBox_number_5->setValue(4);
        spinBox_hp_5 = new QSpinBox(groupBox);
        spinBox_hp_5->setObjectName(QStringLiteral("spinBox_hp_5"));
        spinBox_hp_5->setGeometry(QRect(140, 420, 61, 22));
        spinBox_hp_5->setMaximum(1000);
        spinBox_hp_5->setValue(1000);
        spinBox_size_5 = new QSpinBox(groupBox);
        spinBox_size_5->setObjectName(QStringLiteral("spinBox_size_5"));
        spinBox_size_5->setGeometry(QRect(510, 420, 61, 22));
        spinBox_size_5->setMinimum(1);
        spinBox_size_5->setMaximum(100);
        spinBox_size_5->setValue(40);
        label_type_5 = new QLabel(groupBox);
        label_type_5->setObjectName(QStringLiteral("label_type_5"));
        label_type_5->setGeometry(QRect(30, 410, 40, 40));
        label_type_5->setPixmap(QPixmap(QString::fromUtf8(":/ecosystem/Resources/lion.png")));
        label_type_5->setScaledContents(true);
        spinBox_attackrange_5 = new QSpinBox(groupBox);
        spinBox_attackrange_5->setObjectName(QStringLiteral("spinBox_attackrange_5"));
        spinBox_attackrange_5->setGeometry(QRect(390, 420, 61, 22));
        spinBox_attackrange_5->setMinimum(0);
        spinBox_attackrange_5->setMaximum(100);
        spinBox_attackrange_5->setValue(10);
        spinBox_speed_5 = new QSpinBox(groupBox);
        spinBox_speed_5->setObjectName(QStringLiteral("spinBox_speed_5"));
        spinBox_speed_5->setGeometry(QRect(260, 420, 61, 22));
        spinBox_speed_5->setMinimum(1);
        spinBox_speed_5->setMaximum(100);
        spinBox_speed_5->setValue(20);
        label_14 = new QLabel(groupBox);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(740, 267, 72, 21));
        label_14->setLayoutDirection(Qt::LeftToRight);
        spinBox_number_6 = new QSpinBox(groupBox);
        spinBox_number_6->setObjectName(QStringLiteral("spinBox_number_6"));
        spinBox_number_6->setGeometry(QRect(630, 270, 61, 22));
        spinBox_number_6->setMinimum(0);
        spinBox_number_6->setMaximum(100);
        spinBox_number_6->setValue(10);
        spinBox_hp_6 = new QSpinBox(groupBox);
        spinBox_hp_6->setObjectName(QStringLiteral("spinBox_hp_6"));
        spinBox_hp_6->setGeometry(QRect(140, 270, 61, 22));
        spinBox_hp_6->setMaximum(1000);
        spinBox_hp_6->setValue(1000);
        spinBox_size_6 = new QSpinBox(groupBox);
        spinBox_size_6->setObjectName(QStringLiteral("spinBox_size_6"));
        spinBox_size_6->setGeometry(QRect(510, 270, 61, 22));
        spinBox_size_6->setMinimum(1);
        spinBox_size_6->setMaximum(100);
        spinBox_size_6->setValue(35);
        label_type_6 = new QLabel(groupBox);
        label_type_6->setObjectName(QStringLiteral("label_type_6"));
        label_type_6->setGeometry(QRect(30, 260, 40, 40));
        label_type_6->setPixmap(QPixmap(QString::fromUtf8(":/ecosystem/Resources/pig.png")));
        label_type_6->setScaledContents(true);
        spinBox_attackrange_6 = new QSpinBox(groupBox);
        spinBox_attackrange_6->setObjectName(QStringLiteral("spinBox_attackrange_6"));
        spinBox_attackrange_6->setGeometry(QRect(390, 270, 61, 22));
        spinBox_attackrange_6->setMinimum(0);
        spinBox_attackrange_6->setMaximum(100);
        spinBox_attackrange_6->setValue(0);
        spinBox_speed_6 = new QSpinBox(groupBox);
        spinBox_speed_6->setObjectName(QStringLiteral("spinBox_speed_6"));
        spinBox_speed_6->setGeometry(QRect(260, 270, 61, 22));
        spinBox_speed_6->setMinimum(1);
        spinBox_speed_6->setMaximum(100);
        spinBox_speed_6->setValue(20);
        label_15 = new QLabel(groupBox);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(740, 367, 72, 21));
        label_15->setLayoutDirection(Qt::LeftToRight);
        spinBox_number_7 = new QSpinBox(groupBox);
        spinBox_number_7->setObjectName(QStringLiteral("spinBox_number_7"));
        spinBox_number_7->setGeometry(QRect(630, 370, 61, 22));
        spinBox_number_7->setMinimum(0);
        spinBox_number_7->setMaximum(100);
        spinBox_number_7->setValue(4);
        spinBox_hp_7 = new QSpinBox(groupBox);
        spinBox_hp_7->setObjectName(QStringLiteral("spinBox_hp_7"));
        spinBox_hp_7->setGeometry(QRect(140, 370, 61, 22));
        spinBox_hp_7->setMaximum(1000);
        spinBox_hp_7->setValue(1000);
        spinBox_size_7 = new QSpinBox(groupBox);
        spinBox_size_7->setObjectName(QStringLiteral("spinBox_size_7"));
        spinBox_size_7->setGeometry(QRect(510, 370, 61, 22));
        spinBox_size_7->setMinimum(1);
        spinBox_size_7->setMaximum(100);
        spinBox_size_7->setValue(40);
        label_type_7 = new QLabel(groupBox);
        label_type_7->setObjectName(QStringLiteral("label_type_7"));
        label_type_7->setGeometry(QRect(30, 360, 40, 40));
        label_type_7->setPixmap(QPixmap(QString::fromUtf8(":/ecosystem/Resources/tiger.png")));
        label_type_7->setScaledContents(true);
        spinBox_attackrange_7 = new QSpinBox(groupBox);
        spinBox_attackrange_7->setObjectName(QStringLiteral("spinBox_attackrange_7"));
        spinBox_attackrange_7->setGeometry(QRect(390, 370, 61, 22));
        spinBox_attackrange_7->setMinimum(0);
        spinBox_attackrange_7->setMaximum(100);
        spinBox_attackrange_7->setValue(10);
        spinBox_speed_7 = new QSpinBox(groupBox);
        spinBox_speed_7->setObjectName(QStringLiteral("spinBox_speed_7"));
        spinBox_speed_7->setGeometry(QRect(260, 370, 61, 22));
        spinBox_speed_7->setMinimum(1);
        spinBox_speed_7->setMaximum(100);
        spinBox_speed_7->setValue(20);
        spinBox_speed_8 = new QSpinBox(groupBox);
        spinBox_speed_8->setObjectName(QStringLiteral("spinBox_speed_8"));
        spinBox_speed_8->setGeometry(QRect(260, 320, 61, 22));
        spinBox_speed_8->setMinimum(1);
        spinBox_speed_8->setMaximum(100);
        spinBox_speed_8->setValue(20);
        label_16 = new QLabel(groupBox);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(740, 317, 72, 21));
        label_16->setLayoutDirection(Qt::LeftToRight);
        spinBox_hp_8 = new QSpinBox(groupBox);
        spinBox_hp_8->setObjectName(QStringLiteral("spinBox_hp_8"));
        spinBox_hp_8->setGeometry(QRect(140, 320, 61, 22));
        spinBox_hp_8->setMaximum(1000);
        spinBox_hp_8->setValue(1000);
        spinBox_size_8 = new QSpinBox(groupBox);
        spinBox_size_8->setObjectName(QStringLiteral("spinBox_size_8"));
        spinBox_size_8->setGeometry(QRect(510, 320, 61, 22));
        spinBox_size_8->setMinimum(1);
        spinBox_size_8->setMaximum(100);
        spinBox_size_8->setValue(35);
        label_type_8 = new QLabel(groupBox);
        label_type_8->setObjectName(QStringLiteral("label_type_8"));
        label_type_8->setGeometry(QRect(30, 310, 40, 40));
        label_type_8->setPixmap(QPixmap(QString::fromUtf8(":/ecosystem/Resources/wolf.png")));
        label_type_8->setScaledContents(true);
        spinBox_attackrange_8 = new QSpinBox(groupBox);
        spinBox_attackrange_8->setObjectName(QStringLiteral("spinBox_attackrange_8"));
        spinBox_attackrange_8->setGeometry(QRect(390, 320, 61, 22));
        spinBox_attackrange_8->setMinimum(0);
        spinBox_attackrange_8->setMaximum(100);
        spinBox_attackrange_8->setValue(10);
        spinBox_number_8 = new QSpinBox(groupBox);
        spinBox_number_8->setObjectName(QStringLiteral("spinBox_number_8"));
        spinBox_number_8->setGeometry(QRect(630, 320, 61, 22));
        spinBox_number_8->setMinimum(0);
        spinBox_number_8->setMaximum(100);
        spinBox_number_8->setValue(4);
        groupBox_2 = new QGroupBox(Dialog);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(20, 480, 851, 201));
        groupBox_2->setFont(font1);
        label = new QLabel(groupBox_2);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(30, 40, 91, 21));
        QFont font2;
        font2.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221 Light"));
        font2.setPointSize(11);
        label->setFont(font2);
        spinBox_mapWidth = new QSpinBox(groupBox_2);
        spinBox_mapWidth->setObjectName(QStringLiteral("spinBox_mapWidth"));
        spinBox_mapWidth->setGeometry(QRect(130, 40, 71, 22));
        QFont font3;
        font3.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221 Light"));
        spinBox_mapWidth->setFont(font3);
        spinBox_mapWidth->setMinimum(100);
        spinBox_mapWidth->setMaximum(1920);
        spinBox_mapWidth->setValue(900);
        label_17 = new QLabel(groupBox_2);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(210, 43, 16, 16));
        label_17->setFont(font3);
        spinBox_mapHeight = new QSpinBox(groupBox_2);
        spinBox_mapHeight->setObjectName(QStringLiteral("spinBox_mapHeight"));
        spinBox_mapHeight->setGeometry(QRect(230, 40, 71, 22));
        spinBox_mapHeight->setFont(font3);
        spinBox_mapHeight->setMinimum(100);
        spinBox_mapHeight->setMaximum(1920);
        spinBox_mapHeight->setValue(600);
        label_18 = new QLabel(groupBox_2);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(500, 40, 191, 21));
        label_18->setFont(font2);
        spinBox_boneTime = new QSpinBox(groupBox_2);
        spinBox_boneTime->setObjectName(QStringLiteral("spinBox_boneTime"));
        spinBox_boneTime->setGeometry(QRect(700, 40, 61, 22));
        spinBox_boneTime->setFont(font3);
        spinBox_boneTime->setMinimum(1);
        spinBox_boneTime->setMaximum(30);
        spinBox_boneTime->setValue(8);
        spinBox_ageTime = new QSpinBox(groupBox_2);
        spinBox_ageTime->setObjectName(QStringLiteral("spinBox_ageTime"));
        spinBox_ageTime->setGeometry(QRect(250, 80, 71, 22));
        spinBox_ageTime->setFont(font3);
        spinBox_ageTime->setMinimum(1);
        spinBox_ageTime->setMaximum(100);
        spinBox_ageTime->setValue(10);
        label_19 = new QLabel(groupBox_2);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(30, 80, 201, 21));
        label_19->setFont(font2);
        spinBox_reproduceAge = new QSpinBox(groupBox_2);
        spinBox_reproduceAge->setObjectName(QStringLiteral("spinBox_reproduceAge"));
        spinBox_reproduceAge->setGeometry(QRect(600, 80, 71, 22));
        spinBox_reproduceAge->setFont(font3);
        spinBox_reproduceAge->setMinimum(1);
        spinBox_reproduceAge->setMaximum(100);
        spinBox_reproduceAge->setValue(5);
        label_20 = new QLabel(groupBox_2);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(500, 80, 91, 21));
        label_20->setFont(font2);
        label_21 = new QLabel(groupBox_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(30, 120, 141, 21));
        label_21->setFont(font2);
        spinBox_reproduceHp = new QSpinBox(groupBox_2);
        spinBox_reproduceHp->setObjectName(QStringLiteral("spinBox_reproduceHp"));
        spinBox_reproduceHp->setGeometry(QRect(190, 120, 61, 22));
        spinBox_reproduceHp->setFont(font3);
        spinBox_reproduceHp->setMinimum(1);
        spinBox_reproduceHp->setMaximum(100);
        spinBox_reproduceHp->setValue(80);
        label_22 = new QLabel(groupBox_2);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(260, 120, 21, 21));
        label_22->setFont(font2);
        label_23 = new QLabel(groupBox_2);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(710, 120, 21, 21));
        label_23->setFont(font2);
        spinBox_reproduceProportion = new QSpinBox(groupBox_2);
        spinBox_reproduceProportion->setObjectName(QStringLiteral("spinBox_reproduceProportion"));
        spinBox_reproduceProportion->setGeometry(QRect(640, 120, 61, 22));
        spinBox_reproduceProportion->setFont(font3);
        spinBox_reproduceProportion->setMinimum(1);
        spinBox_reproduceProportion->setMaximum(100);
        spinBox_reproduceProportion->setValue(40);
        label_24 = new QLabel(groupBox_2);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(500, 120, 141, 21));
        label_24->setFont(font2);
        spinBox_ageLimit = new QSpinBox(groupBox_2);
        spinBox_ageLimit->setObjectName(QStringLiteral("spinBox_ageLimit"));
        spinBox_ageLimit->setGeometry(QRect(170, 160, 71, 22));
        spinBox_ageLimit->setFont(font3);
        spinBox_ageLimit->setMinimum(1);
        spinBox_ageLimit->setMaximum(2000);
        spinBox_ageLimit->setValue(100);
        label_25 = new QLabel(groupBox_2);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(30, 160, 131, 21));
        label_25->setFont(font2);
        spinBox_numberLimit = new QSpinBox(groupBox_2);
        spinBox_numberLimit->setObjectName(QStringLiteral("spinBox_numberLimit"));
        spinBox_numberLimit->setGeometry(QRect(640, 160, 71, 22));
        spinBox_numberLimit->setFont(font3);
        spinBox_numberLimit->setMinimum(1);
        spinBox_numberLimit->setMaximum(130);
        spinBox_numberLimit->setValue(130);
        label_26 = new QLabel(groupBox_2);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(500, 160, 131, 21));
        label_26->setFont(font2);
        splitter = new QSplitter(Dialog);
        splitter->setObjectName(QStringLiteral("splitter"));
        splitter->setGeometry(QRect(250, 690, 541, 51));
        splitter->setOrientation(Qt::Horizontal);
        pushButton_rand = new QPushButton(splitter);
        pushButton_rand->setObjectName(QStringLiteral("pushButton_rand"));
        splitter->addWidget(pushButton_rand);
        pushButton_ok = new QPushButton(splitter);
        pushButton_ok->setObjectName(QStringLiteral("pushButton_ok"));
        splitter->addWidget(pushButton_ok);
        pushButton_load = new QPushButton(splitter);
        pushButton_load->setObjectName(QStringLiteral("pushButton_load"));
        splitter->addWidget(pushButton_load);
        pushButton_save = new QPushButton(splitter);
        pushButton_save->setObjectName(QStringLiteral("pushButton_save"));
        splitter->addWidget(pushButton_save);
        pushButton = new QPushButton(Dialog);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(120, 690, 121, 51));

        retranslateUi(Dialog);
        QObject::connect(pushButton_rand, SIGNAL(clicked()), Dialog, SLOT(btnRandClick()));
        QObject::connect(pushButton_ok, SIGNAL(clicked()), Dialog, SLOT(btnOkClick()));
        QObject::connect(pushButton_load, SIGNAL(clicked()), Dialog, SLOT(btnLoadClick()));
        QObject::connect(pushButton_save, SIGNAL(clicked()), Dialog, SLOT(btnSaveClick()));
        QObject::connect(pushButton, SIGNAL(clicked()), Dialog, SLOT(btnDefaultSettingClick()));

        QMetaObject::connectSlotsByName(Dialog);
    } // setupUi

    void retranslateUi(QDialog *Dialog)
    {
        Dialog->setWindowTitle(QApplication::translate("Dialog", "Setting", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("Dialog", "\345\212\250\347\211\251", Q_NULLPTR));
        label_2->setText(QApplication::translate("Dialog", "\347\247\215\347\261\273", Q_NULLPTR));
        label_3->setText(QApplication::translate("Dialog", "\350\241\200\351\207\217", Q_NULLPTR));
        label_type->setText(QString());
        label_4->setText(QApplication::translate("Dialog", "\347\247\273\345\212\250\351\200\237\345\272\246", Q_NULLPTR));
        label_5->setText(QApplication::translate("Dialog", "\346\224\273\345\207\273\350\214\203\345\233\264", Q_NULLPTR));
        label_6->setText(QApplication::translate("Dialog", "\344\275\223\345\236\213", Q_NULLPTR));
        label_7->setText(QApplication::translate("Dialog", "\346\225\260\351\207\217", Q_NULLPTR));
        label_8->setText(QApplication::translate("Dialog", "\351\243\237\347\211\251\351\223\276\347\255\211\347\272\247", Q_NULLPTR));
        label_9->setText(QApplication::translate("Dialog", "<html><head/><body><p align=\"center\">1</p></body></html>", Q_NULLPTR));
        label_10->setText(QApplication::translate("Dialog", "<html><head/><body><p align=\"center\">1</p></body></html>", Q_NULLPTR));
        label_type_2->setText(QString());
        label_11->setText(QApplication::translate("Dialog", "<html><head/><body><p align=\"center\">1</p></body></html>", Q_NULLPTR));
        label_type_3->setText(QString());
        label_12->setText(QApplication::translate("Dialog", "<html><head/><body><p align=\"center\">1</p></body></html>", Q_NULLPTR));
        label_type_4->setText(QString());
        label_13->setText(QApplication::translate("Dialog", "<html><head/><body><p align=\"center\">4</p></body></html>", Q_NULLPTR));
        label_type_5->setText(QString());
        label_14->setText(QApplication::translate("Dialog", "<html><head/><body><p align=\"center\">1</p></body></html>", Q_NULLPTR));
        label_type_6->setText(QString());
        label_15->setText(QApplication::translate("Dialog", "<html><head/><body><p align=\"center\">3</p></body></html>", Q_NULLPTR));
        label_type_7->setText(QString());
        label_16->setText(QApplication::translate("Dialog", "<html><head/><body><p align=\"center\">2</p></body></html>", Q_NULLPTR));
        label_type_8->setText(QString());
        groupBox_2->setTitle(QApplication::translate("Dialog", "\345\205\266\344\273\226", Q_NULLPTR));
        label->setText(QApplication::translate("Dialog", "\345\234\260\345\233\276\345\244\247\345\260\217\357\274\232", Q_NULLPTR));
        label_17->setText(QApplication::translate("Dialog", "X", Q_NULLPTR));
        label_18->setText(QApplication::translate("Dialog", "\346\255\273\344\272\241\346\240\207\345\277\227\345\201\234\347\225\231\346\227\266\351\227\264(\347\247\222)\357\274\232", Q_NULLPTR));
        label_19->setText(QApplication::translate("Dialog", "\345\271\264\351\276\204\345\242\236\351\225\277\351\227\264\351\232\224(\345\215\225\344\275\215\346\227\266\351\227\264)\357\274\232", Q_NULLPTR));
        label_20->setText(QApplication::translate("Dialog", "\347\271\201\346\256\226\345\271\264\351\276\204\357\274\232", Q_NULLPTR));
        label_21->setText(QApplication::translate("Dialog", "\347\271\201\346\256\226\351\234\200\350\246\201\347\232\204\350\241\200\351\207\217\357\274\232", Q_NULLPTR));
        label_22->setText(QApplication::translate("Dialog", "%", Q_NULLPTR));
        label_23->setText(QApplication::translate("Dialog", "%", Q_NULLPTR));
        label_24->setText(QApplication::translate("Dialog", "\347\271\201\346\256\226\346\210\220\345\212\237\346\246\202\347\216\207\357\274\232", Q_NULLPTR));
        label_25->setText(QApplication::translate("Dialog", "\345\212\250\347\211\251\345\271\264\351\276\204\351\231\220\345\210\266\357\274\232", Q_NULLPTR));
        label_26->setText(QApplication::translate("Dialog", "\345\212\250\347\211\251\346\225\260\351\207\217\351\231\220\345\210\266\357\274\232", Q_NULLPTR));
        pushButton_rand->setText(QApplication::translate("Dialog", "\351\232\217\346\234\272\347\224\237\346\210\220\346\225\260\351\207\217", Q_NULLPTR));
        pushButton_ok->setText(QApplication::translate("Dialog", "\347\241\256\345\256\232", Q_NULLPTR));
        pushButton_load->setText(QApplication::translate("Dialog", "\345\257\274\345\205\245", Q_NULLPTR));
        pushButton_save->setText(QApplication::translate("Dialog", "\345\257\274\345\207\272", Q_NULLPTR));
        pushButton->setText(QApplication::translate("Dialog", "\346\201\242\345\244\215\351\273\230\350\256\244", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class Dialog: public Ui_Dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DIALOGSETTING_H
